### ISSUE TITLE
powerup description

### ISSUE THREAD

**Issue by cgalle1** [Shudouken/ball51#1]
not every power up or facility was clear - 1 - you had easy levels to introduce new items but a little textual description would also be nice.

**Comment by widnig89** [comment]
@cgalle1 : könnten wir bei mousehover [1] einrichten, sodass ein tooltip kommt wenn er drüber fährt (englische description + ev. restrictions e.g shrink, scale --> nur eins möglich)


[1](http://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseOver.html)

**Comment by widnig89** [comment]
@cgalle1 hab das nun implementiert, bitte eine description überall dazuschreiben bei jedem prefab in der komponente objectBehaviourScript (e.g. siehe antigravity powerup description) -> bei facilities auch bitte

**Comment by cgalle1** [comment]
finde die antigravity powerup description nicht

**Comment by cgalle1** [comment]
habs
