### ISSUE TITLE
level sort

### ISSUE THREAD

**Issue by cgalle1** [Shudouken/ball51#3]
Some low levels (like 2nd) are a bit hard (maybe try to add some new levels in between)

**Comment by widnig89** [comment]
@gfraissler : kannst du zum schluss einige levels neu machen? wie schon im anderen issue erwähnt[1] sollten die neuen auch gleich so umgesetzt werden. aber machen wir sie bitte wirklich zum schluss (letzten 2 tage) wenn das canvas steht + alle elemente und gib vorher bescheid bitte

[1] https://github.com/Shudouken/ball51/issues/4

**Comment by widnig89** [comment]
24 levels sind max möglich (wegen level selection screen)

**Comment by widnig89** [comment]
done
