### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by cgalle1** [Shudouken/ball51#4]
Give user a feedback if he fails a level
Give user a feedback if he succeed a level

**Comment by widnig89** [comment]
level design sollte so gemacht werden, dass kein ball mehr aus dem screen fallen kann. d.h. komplett umrandet (lava sollte dann implementiert werden @spiderpigX  kannst du das sprite machen. @Shudouken du das script dazu (die methode fail() kann ruhig leer sein, ev. mit debug output. ich machs dann mit der logik wenns früh genug umgesetzt wird?

**Comment by widnig89** [comment]
if he succeeds he will be notified with a dialog and that he can enter the next level
